server:
  port: 19090
  servlet:
    context-path: /cloud-scheduled-job-admin


spring:
  application:
    name: cloud-scheduled-job-admin


  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/


  #????
  shardingsphere:
    #????sql
    props:
      sql:
        show: false
    #?????
    datasource:
      #?????
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://139.196.208.53:3306/xxl_job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Zs11195310

    sharding:
      # ???????????????????
      default-data-source-name: master
      tables:
        #??????:sharding-jdbc??????????????sql????????????
        xxl_job_log:
          ## ???????sharding?????
          actual-data-nodes: master.xxl_job_log_$->{0..2}
          ## ??????
          key-generator:
            #??????????
            column: id
            #????? ????
            type: SNOWFLAKE
          # ????????????(????)
          table-strategy:
            # ????
            inline:
              # ??sharding????
              sharding-column: id
              # ??sharding????,???id???sharding-column?????????
              algorithm-expression: xxl_job_log_$->{id % 3}


    #elasticsearch??
  elasticsearch:
    rest:
      uris: http://139.196.208.53:9200


  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########


  ###????
  mail:
    host: smtp.qq.com
    ###??????25???????????????????465????????ssl??
    port: 465
    from: 1623517072@qq.com
    username: 1623517072@qq.com
    password: gqdoapqsvjeqccjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory


mybatis-plus:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  type-aliases-package: com.xxl.job.admin.core.model
  configuration:
    map-underscore-to-camel-case: true
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: partial
  global-config:
    db-config:
      id-type: auto


### actuator
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

xxl:
  job:
    accessToken:
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30


#rocketmq??
cloud:
  rocketmq:
    #????name-server
    nameServer: 139.196.208.53:9876
    producer:
      group: p-${spring.application.name}

    consumer:
      #??????
      c-xxl-job-admin:
        subscription:
          #????
          TP_F_FB: EC_RESULT

logging:
  level:
    RocketmqClient: error
    RocketmqRemoting: warn

